version: "3.7"

services:
  api: # Сервис API
    build:
      context: ./
    volumes:
      - static_volume:/home/app/staticfiles
    env_file:
      - .env
    expose:
      - 8000
    restart: always
    depends_on:
      - db
  front:
    build:
      context: ./
    env_file:
      - .env
    expose:
      - 9000
    restart: always
    depends_on:
      - api
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/staticfiles
      - ./nginx:/etc/nginx/conf.d
    ports:
      - "80:80"
    depends_on:
      - api
    env_file:
      - .env
  db:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    volumes:
      - data:/var/lib/postgresql/data
volumes:
  data:
  static_volume:

